_target_: src.models.trainer_image.ImageTrainer

scene_path: '/public/home/wangzh1/iccp2025/mitsuba3-workflow/scenes/cbox.xml'
learning_rate: 0.05
max_stages: 1
max_iterations: 100
val_interval: 10
device: 'cuda'