_target_: src.models.trainer_trans.TransientTrainer

scene_path: '/public/home/wangzh1/iccp2025/cornell-box/cbox_diffuse.xml'
lambda_total: 100
learning_rate: 1
max_stages: 1
max_iterations: 1000
val_interval: 100
device: cuda
